### ISSUE TITLE
Error on pagination query 

### ISSUE THREAD

**Issue by komasini** [sensedeep/dynamodb-onetable#482]
**Describe the bug**

"options.removeUndefinedValues=true" error when using pagination on querying by GSI when PK does not use a SORT key.

I specify a table that only uses a hash key but no sort key for the primary key. The GSI uses hash and sort key.
When I query on the table using pagination the followup request using the `next` param fails.

Error Output (from adjusted test suite):
```
  ● Find with next offset

    Pass options.removeUndefinedValues=true to remove undefined values from map/array/set.

      1054 |                 }
      1055 |             } else {
    > 1056 |                 item = client.marshall(item, options)
           |                               ^
      1057 |             }
      1058 |         } else {
      1059 |             if (Array.isArray(item)) {

      at convertToAttr (node_modules/@aws-sdk/util-dynamodb/dist-cjs/convertToAttr.js:7:15)
      at node_modules/@aws-sdk/util-dynamodb/dist-cjs/convertToAttr.js:118:54
      at convertToMapAttrFromEnumerableProps (node_modules/@aws-sdk/util-dynamodb/dist-cjs/convertToAttr.js:122:7)
      at convertToAttr (node_modules/@aws-sdk/util-dynamodb/dist-cjs/convertToAttr.js:23:16)
      at Dynamo.marshall (node_modules/@aws-sdk/util-dynamodb/dist-cjs/marshall.js:6:62)
      at Table.marshall (src/Table.js:1056:31)
      at Expression.command (src/Expression.js:616:57)
      at Model.run (src/Model.js:289:30)
      at Model.queryItems (src/Model.js:1005:27)
      at Model.find (src/Model.js:630:27)
      at Object.<anonymous> (test/pagination.ts:54:28)
```

**To Reproduce**

I adjusted `pagination.ts` test case as follows (commented out and replaced one line each file):
Adjusted schema (to use a PK with only a hash key):
```
export default {
    format: 'onetable:1.1.0',
    version: '0.0.1',
    indexes: {
        //primary: {hash: 'pk', sort: 'sk'},
        primary: {hash: 'sk'},
        gs1: {hash: 'gs1pk', sort: 'gs1sk'},
    },
    models: {
        User: {
            pk: {type: String, value: '${_type}#'},
            sk: {type: String, value: '${_type}#${name}'},
            id: {type: String, generate: 'ulid'},

            name: {type: String, required: true},
            email: {type: String, required: true},

            gs1pk: {type: String, value: '${_type}#'},
            gs1sk: {type: String, value: '${_type}#${email}'},
        },
    },
}
```

Adjusted test case (to use the index on the most general pagination test case):
```
test('Find with next offset', async () => {
    let pages = 0,
        total = 0,
        next
    let items: any
    do {
        //items = await User.find({}, {limit: PerPage, next})
        items = await User.find({}, {limit: PerPage, next, index: 'gs1'})
        if (items.length) {
            expect(items[0].name).toBe(`user-${zpad(total, 6)}`)
            expect(items[0].email).toBe(`email-${zpad(total, 6)}@example.com`)
            total += items.length
            pages++
        }
        next = items.next
    } while (next)

    expect(total).toBe(MaxUsers)
    expect(pages).toBe(MaxUsers / PerPage)
})
```

(I am a newbie in regard to DynamoDb, so maybe I am doing something wrong. Regarding the general setup, I intend to use the primary key only for direct lookups, not for scans/queries, not sure yet if that will be useful in the end...)

**Comment by mobsense** [comment]
Thank you for submitting. Fix committed.

**Comment by spacem** [comment]
Getting this issue still in 2.7.1, I believe the problem still occurs when querying an index that has no sort key

**Comment by mobsense** [comment]
Can you please submit a debug.ts test case that demonstrates this. The test case above works.
